### ISSUE TITLE
Typo in package.json

### ISSUE THREAD

**Issue by amperie** [Appdynamics/Node.js-Demo-App#5]
Add a coma at the end of this line:

 "mysql": "2.4.2"

otherwise "npm install" will fail.

**Comment by kemety** [comment]
I followed the instructions carefully. I am running Mint/Ubuntu 16.10 - I get a lot of errors running:"npm install" and when running later node "server.js" it gives the below error
`{
    "err": "Error: Cannot find module './routes/movie'\n    at Function.Module._resolveFilename (module.js:469:15)\n    at Function.Module._load (module.js:417:25)\n    at Module.require (module.js:497:17)\n    at Module.obj.(anonymous function) [as require] (/opt/acme-wine-cellar/node_modules/appdynamics/lib/core/proxy.js:216:22)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/opt/acme-wine-cellar/server.js:14:13)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)",
    "t": "24-11-2016 23:39:32.099"
  }
`
